### ISSUE TITLE
A new release 1.0.3 to support Swift Packages

### ISSUE THREAD

**Issue by woolie** [mehrankmlf/SecurityKit#5]
The new Swift package support has not been released. I wonder if it is possible to make a 1.0.3 release so that the Package.swift version is available?

Thanks in advance.

**Comment by mehrankmlf** [comment]
hello sir, Due to the details that you mentioned version 1.0.3 is required to publish with changes to support the new Swift package.

**Comment by woolie** [comment]
Exactly. I am asking if you can make the new release. Please.

**Comment by mehrankmlf** [comment]
sure, as soon as possible

**Comment by mehrankmlf** [comment]
Hello, sir. I have just released version 1.0.3, which now includes support for SPM and addresses the uppercase issues in methods. I apologize for the delayed response; I was deeply immersed in developing the PassGuard framework, which was just published yesterday. I would greatly appreciate your feedback and any advice you may have regarding the PassGuard framework. Thank you!

https://github.com/mehrankmlf/PassGuard

**Comment by woolie** [comment]
Thank you. I will check out PassGuard.
